version: '3.8'

services:

  redis:
    image: redis:alpine

  django:
    container_name: django
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8001:8000
    environment:
    - DEBUG=1
    - SECRET_KEY=django-insecure-#(secret key)
    - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app=core worker -l INFO
    volumes:
      - ./backend:/app
    environment:
    - DEBUG=1
    - SECRET_KEY=django-insecure-#(secret key)
    - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis